// vue-example/src/App.vue
<script>
import axios from 'axios'
import Question from './components/Question.vue'

export default {
    components: {
        Question
    },
    data() {
        return {
            questions: []
        }
    },
    mounted () {
        axios.get('/api').then(response => (this.questions = response.data.data));
    }
}

//const questions = [1, 2, 3];
</script>

<template>
    <div v-for="question in questions">
        <Question :item="question" />
    </div>
</template>

<style>
</style>

// react-example/src/App.js
import logo from './logo.svg';
import './App.css';

import { useEffect, useState } from "react";

import Question from "./components/Question";

function App() {
  const [data, setData] = useState();

  async function getData() {
      const response = await fetch('/api');
      const data = await response.json();
      return data;
  }

  useEffect(() => {
      getData().then((data) => {
          setData(data);
      });
  }, []);

  return (
      <>
      {data && data.data.map((value, index) =>
        <Question key={index} item={value} />
      )}
      </>
  );
}

export default App;
