// vue-example/src/components/Question.vue
<script>
export default {
    props: ['item'],
}
</script>

<template>
    <h2>{{ item.text }}</h2>
    <ul v-for="choice in item.choices">
        <li>{{ choice }}</li>
    </ul>
    <h3>{{ item.answer }}</h3>
    <div id="line"></div>
</template>

<style scoped>
    #line {
        border: black solid 2px;
    }
</style>

// react-example/src/components/Question.jsx
function Question(props) {
    return (
        <>
           <h2>{props.item.text}</h2>
           <ul>
            {props.item.choices.map((value, index) => 
                (<li key={index}>{value}</li>)
            )}
           </ul>
           <h3>{props.item.answer}</h3>
           <div id="line"></div>
        </>
    )
}

export default Question;
